"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sample_users = exports.sample_tags = exports.sample_foods = void 0;
exports.sample_foods = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food1.jpg',
        tags: ['Italy', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Hamburger',
        price: 20,
        cookTime: '10-20',
        favorite: true,
        origins: ['germany', 'us'],
        stars: 4.7,
        imageUrl: 'assets/food2.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '3',
        name: 'Sushi',
        price: 5,
        cookTime: '5-10',
        favorite: false,
        origins: ['japan'],
        stars: 3.5,
        imageUrl: 'assets/food3.jpg',
        tags: ['FastFood', 'Japan'],
    },
    {
        id: '4',
        name: 'Spaghetti Bolognese',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['italy'],
        stars: 3.3,
        imageUrl: 'assets/food4.jpeg',
        tags: ['Italy', 'Pasta'],
    },
    {
        id: '5',
        name: 'Schnitzel',
        price: 11,
        cookTime: '20-30',
        favorite: false,
        origins: ['austria'],
        stars: 3.0,
        imageUrl: 'assets/food5.jpg',
        tags: ['Austria', 'Meat'],
    },
    {
        id: '6',
        name: 'Tacos',
        price: 9,
        cookTime: '15-20',
        favorite: false,
        origins: ['mexico'],
        stars: 4.0,
        imageUrl: 'assets/food6.jpg',
        tags: ['SlowFood', 'Mexican']
    },
    {
        id: '7',
        name: 'Pizza Margherita',
        price: 10,
        cookTime: '10-20',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food7.jpg',
        tags: ['Italy', 'Pizza', 'Lunch'],
    },
    {
        id: '8',
        name: 'French Fries',
        price: 20,
        cookTime: '10-20',
        favorite: true,
        origins: ['france'],
        stars: 4.7,
        imageUrl: 'assets/food8.jpg',
        tags: ['France', 'Fry'],
    },
    {
        id: '9',
        name: 'Piroshki',
        price: 5,
        cookTime: '5-10',
        favorite: false,
        origins: ['russia'],
        stars: 3.5,
        imageUrl: 'assets/food9.jpg',
        tags: ['FastFood', 'Russia'],
    },
    {
        id: '10',
        name: 'Poutine',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['canada'],
        stars: 3.3,
        imageUrl: 'assets/food10.jpg',
        tags: ['Canada', 'Poutine'],
    },
    {
        id: '11',
        name: 'Meatballs',
        price: 11,
        cookTime: '20-30',
        favorite: false,
        origins: ['sweden'],
        stars: 3.0,
        imageUrl: 'assets/food11.jpg',
        tags: ['Sweden', 'Meat'],
    },
    {
        id: '12',
        name: 'Pancakes',
        price: 9,
        cookTime: '15-20',
        favorite: false,
        origins: ['usa'],
        stars: 4.0,
        imageUrl: 'assets/food12.jpg',
        tags: ['SlowFood', 'American']
    },
    {
        id: '13',
        name: 'Nagari',
        price: 10,
        cookTime: '10-20',
        favorite: false,
        origins: ['japan'],
        stars: 4.5,
        imageUrl: 'assets/food13.jpg',
        tags: ['FastFood', 'Japan', 'Lunch'],
    },
    {
        id: '14',
        name: 'Chicken Soup',
        price: 20,
        cookTime: '10-20',
        favorite: true,
        origins: ['International'],
        stars: 4.7,
        imageUrl: 'assets/food14.jpg',
        tags: ['International', 'Soup'],
    },
    {
        id: '15',
        name: 'Cheeseburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['usa'],
        stars: 3.5,
        imageUrl: 'assets/food15.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '16',
        name: 'Veggies Pizza',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['italy'],
        stars: 3.3,
        imageUrl: 'assets/food16.jpg',
        tags: ['SlowFood', 'Pizza'],
    }
];
exports.sample_tags = [
    { name: 'All', count: 6 },
    { name: 'Mexican', count: 1 },
    { name: 'American', count: 1 },
    { name: 'Japan', count: 2 },
    { name: 'Russia', count: 1 },
    { name: 'Canada', count: 1 },
    { name: 'Sweden', count: 1 },
    { name: 'International', count: 1 },
    { name: 'Italy', count: 3 },
    { name: 'France', count: 1 },
    { name: 'Austria', count: 1 },
];
exports.sample_users = [
    {
        name: "John Doe",
        email: "john@gmail.com",
        password: "12345",
        address: "Toronto On",
        isAdmin: true,
    },
    {
        name: "Jane Doe",
        email: "Jane@gmail.com",
        password: "12345",
        address: "Shanghai",
        isAdmin: false,
    },
];
